CREATE DATABASE deteccao_facial;
GO

USE deteccao_facial
GO


--TIPO USUARIO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	tipo VARCHAR(70) UNIQUE NOT NULL
);
GO

CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(256) NOT NULL,
	senha VARCHAR(18) NOT NULL CHECK( len(senha) >= 8)
);
GO